"""Report export system for the Rare Disease Diagnostic Agent.

Supports four export formats:
  - export_markdown()      -- structured clinical Markdown report
  - export_json()          -- machine-readable JSON
  - export_pdf()           -- styled PDF via ReportLab Platypus
  - export_fhir_r4()       -- FHIR R4 DiagnosticReport Bundle + GA4GH Phenopacket stub

Plus specialised report generators:
  - export_diagnostic_report()  -- phenotype-driven differential diagnosis
  - export_variant_report()     -- ACMG variant interpretation
  - export_therapy_report()     -- gene therapy eligibility

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import io
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Union

logger = logging.getLogger(__name__)

VERSION = "1.0.0"


# ===================================================================
# REPORT TEMPLATES (Markdown fragments)
# ===================================================================

REPORT_TEMPLATES: Dict[str, str] = {
    "diagnostic": (
        "# Rare Disease Diagnostic Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Diagnostic Assessment  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "variant": (
        "# Variant Interpretation Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** ACMG Variant Classification  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "therapy": (
        "# Gene Therapy Eligibility Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Therapy Eligibility Assessment  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "workflow": (
        "# Rare Disease Workflow Report\n\n"
        "**Report Type:** {workflow_type}  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
}

_DISCLAIMER = (
    "\n\n---\n\n"
    "> **Disclaimer:** This report is generated by the HCLS AI Factory "
    "Rare Disease Diagnostic Agent for decision-support purposes "
    "only. It does not constitute medical advice and must "
    "be reviewed by qualified clinical geneticists before any "
    "diagnostic or therapeutic action is taken.\n"
)


# ===================================================================
# HELPER FUNCTIONS
# ===================================================================


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_display() -> str:
    """Return a human-friendly UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _generate_filename(prefix: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{ts}.{extension}"


# ===================================================================
# MAIN EXPORTER CLASS
# ===================================================================


class RareDiseaseReportExporter:
    """Multi-format report exporter for the Rare Disease Diagnostic Agent.

    Produces reports in Markdown, JSON, PDF, and FHIR R4 formats.

    Usage::

        exporter = RareDiseaseReportExporter()
        md = exporter.export_diagnostic_report(findings, patient_id="P-001")
        pdf_bytes = exporter.export_pdf(report_data)
        fhir = exporter.export_fhir_r4(report_data)
    """

    # -- Diagnostic Report --

    def export_diagnostic_report(
        self,
        findings: List[str],
        differential: List[Dict[str, Any]] = None,
        patient_id: str = "DEMO",
        phenotypes: List[str] = None,
        format_type: str = "markdown",
    ) -> Union[str, dict]:
        """Export a phenotype-driven differential diagnosis report.

        Args:
            findings: Key clinical findings.
            differential: List of candidate diagnoses with scores.
            patient_id: Patient identifier.
            phenotypes: Observed HPO phenotypes.
            format_type: Output format ("markdown" or "json").

        Returns:
            Markdown string or JSON dict.
        """
        differential = differential or []
        phenotypes = phenotypes or []
        timestamp = _now_display()

        if format_type == "json":
            return {
                "report_type": "diagnostic",
                "patient_id": patient_id,
                "generated_at": _now_iso(),
                "version": VERSION,
                "phenotypes": phenotypes,
                "findings": findings,
                "differential_count": len(differential),
                "differential": differential,
            }

        header = REPORT_TEMPLATES["diagnostic"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]

        if phenotypes:
            lines.append("## Observed Phenotypes\n")
            for p in phenotypes:
                lines.append(f"- {p}")
            lines.append("")

        if findings:
            lines.append("## Key Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if differential:
            lines.append(f"## Differential Diagnosis ({len(differential)} candidates)\n")
            for i, dx in enumerate(differential, 1):
                name = dx.get("disease_name", dx.get("name", "Unknown"))
                score = dx.get("score", 0.0)
                gene = dx.get("gene", "")
                lines.append(f"### {i}. {name}")
                lines.append(f"- **Score:** {score:.0%}")
                if gene:
                    lines.append(f"- **Gene:** {gene}")
                lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Variant Report --

    def export_variant_report(
        self,
        variants: List[Dict[str, Any]],
        patient_id: str = "DEMO",
        format_type: str = "markdown",
    ) -> Union[str, dict]:
        """Export an ACMG variant interpretation report.

        Args:
            variants: List of variant dicts with gene, variant, classification, etc.
            patient_id: Patient identifier.
            format_type: Output format.

        Returns:
            Markdown string or JSON dict.
        """
        timestamp = _now_display()

        if format_type == "json":
            return {
                "report_type": "variant_interpretation",
                "patient_id": patient_id,
                "generated_at": _now_iso(),
                "version": VERSION,
                "variant_count": len(variants),
                "variants": variants,
            }

        header = REPORT_TEMPLATES["variant"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"## Variant Analysis ({len(variants)} variants)\n")

        lines.append("| Gene | Variant | Classification | Evidence |")
        lines.append("|------|---------|---------------|----------|")

        for var in variants:
            gene = var.get("gene", "")
            variant = var.get("variant", "")
            classification = var.get("classification", "VUS")
            evidence = var.get("evidence", "")
            lines.append(f"| {gene} | {variant} | {classification} | {evidence} |")

        lines.append("")
        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Therapy Report --

    def export_therapy_report(
        self,
        therapies: List[Dict[str, Any]],
        patient_id: str = "DEMO",
        diagnosis: str = "",
        gene: str = "",
        format_type: str = "markdown",
    ) -> Union[str, dict]:
        """Export a gene therapy eligibility report.

        Args:
            therapies: List of therapy dicts with eligibility info.
            patient_id: Patient identifier.
            diagnosis: Patient diagnosis.
            gene: Affected gene.
            format_type: Output format.

        Returns:
            Markdown string or JSON dict.
        """
        timestamp = _now_display()

        if format_type == "json":
            return {
                "report_type": "therapy_eligibility",
                "patient_id": patient_id,
                "generated_at": _now_iso(),
                "version": VERSION,
                "diagnosis": diagnosis,
                "gene": gene,
                "therapy_count": len(therapies),
                "therapies": therapies,
            }

        header = REPORT_TEMPLATES["therapy"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        if diagnosis:
            lines.append(f"**Diagnosis:** {diagnosis}  ")
        if gene:
            lines.append(f"**Gene:** {gene}  ")
        lines.append("")
        lines.append(f"## Eligible Therapies ({len(therapies)} found)\n")

        for i, therapy in enumerate(therapies, 1):
            name = therapy.get("drug_name", "Unknown")
            status = therapy.get("approval_status", "")
            eligible = therapy.get("eligible", False)
            reason = therapy.get("reason", "")

            lines.append(f"### {i}. {name}")
            lines.append(f"- **Status:** {status}")
            lines.append(f"- **Eligible:** {'Yes' if eligible else 'No'}")
            if reason:
                lines.append(f"- **Notes:** {reason}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Generic Markdown Export --

    def export_markdown(
        self,
        response: Dict[str, Any],
        report_type: str = "workflow",
    ) -> str:
        """Export a generic workflow response as Markdown.

        Args:
            response: Dict with findings, recommendations, etc.
            report_type: Template key from REPORT_TEMPLATES.

        Returns:
            Markdown report string.
        """
        timestamp = _now_display()
        template_key = report_type if report_type in REPORT_TEMPLATES else "workflow"
        template = REPORT_TEMPLATES[template_key]

        header_vars: Dict[str, str] = {
            "timestamp": timestamp,
            "version": VERSION,
            "patient_id": response.get("patient_id", "DEMO"),
            "workflow_type": report_type.replace("_", " ").title(),
        }

        lines: List[str] = [template.format(**header_vars)]

        findings = response.get("findings", [])
        recommendations = response.get("recommendations", [])
        confidence = response.get("confidence", 0.0)

        lines.append(f"**Confidence:** {confidence:.0%}\n")

        if findings:
            lines.append("## Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- JSON Export --

    def export_json(self, response: Dict[str, Any]) -> dict:
        """Export a clinical response as structured JSON.

        Args:
            response: Dict with clinical data.

        Returns:
            Serialized JSON dict.
        """
        return {
            "report_type": "rare_disease_workflow",
            "generated_at": _now_iso(),
            "version": VERSION,
            "data": response,
        }

    # -- PDF Export --

    def export_pdf(
        self,
        response: Dict[str, Any],
        title: str = "Rare Disease Diagnostic Report",
    ) -> bytes:
        """Export a clinical response as a PDF document.

        Requires ``reportlab``. Returns empty bytes if not available.

        Args:
            response: Dict with findings, recommendations, etc.
            title: Report title.

        Returns:
            PDF file bytes.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            logger.warning("reportlab not installed -- PDF export returning empty bytes")
            return b""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story: List[Any] = []

        story.append(Paragraph(title, styles["Title"]))
        story.append(Spacer(1, 12))
        story.append(
            Paragraph(
                f"Generated: {_now_display()} | Version: {VERSION}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 12))

        for finding in response.get("findings", []):
            story.append(Paragraph(f"Finding: {finding}", styles["Normal"]))
            story.append(Spacer(1, 6))

        for rec in response.get("recommendations", []):
            story.append(Paragraph(f"Recommendation: {rec}", styles["Normal"]))
            story.append(Spacer(1, 6))

        story.append(Spacer(1, 24))
        story.append(
            Paragraph(
                "Disclaimer: This report is for decision-support only.",
                styles["Italic"],
            )
        )

        doc.build(story)
        return buffer.getvalue()

    # -- FHIR R4 Export --

    def export_fhir_r4(
        self,
        response: Dict[str, Any],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export as a FHIR R4 DiagnosticReport Bundle.

        Args:
            response: Dict with findings.
            patient_id: Patient reference.

        Returns:
            FHIR R4 Bundle dictionary.
        """
        report_id = str(uuid.uuid4())
        timestamp = _now_iso()

        findings = response.get("findings", [])
        conclusion = "; ".join(findings[:3]) if findings else ""
        category_code = response.get("workflow_type", "rare_disease_diagnostic")

        diagnostic_report = {
            "resourceType": "DiagnosticReport",
            "id": report_id,
            "status": "final",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://hcls-ai-factory.dev/rd-agent",
                            "code": category_code,
                            "display": category_code.replace("_", " ").title(),
                        }
                    ]
                }
            ],
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "81247-9",
                        "display": "Master HL7 genetic variant reporting panel",
                    }
                ]
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": timestamp,
            "issued": timestamp,
            "conclusion": conclusion,
        }

        bundle = {
            "resourceType": "Bundle",
            "type": "document",
            "timestamp": timestamp,
            "entry": [
                {
                    "resource": diagnostic_report,
                    "fullUrl": f"urn:uuid:{report_id}",
                }
            ],
            "meta": {
                "profile": [
                    "http://hcls-ai-factory.dev/fhir/rare-disease-diagnostic-report"
                ],
                "tag": [
                    {
                        "system": "http://hcls-ai-factory.dev/version",
                        "code": VERSION,
                    }
                ],
            },
        }

        return bundle

    # -- GA4GH Phenopacket Export --

    def export_phenopacket(
        self,
        patient_id: str = "DEMO",
        phenotypes: List[str] = None,
        diagnosis: str = "",
        gene: str = "",
        variants: List[Dict[str, Any]] = None,
    ) -> dict:
        """Export a GA4GH Phenopacket stub.

        Args:
            patient_id: Patient identifier.
            phenotypes: List of HPO term IDs or names.
            diagnosis: Disease diagnosis.
            gene: Affected gene.
            variants: Variant information.

        Returns:
            GA4GH Phenopacket dict.
        """
        phenotypes = phenotypes or []
        variants = variants or []

        phenotypic_features = [
            {
                "type": {
                    "id": p if p.startswith("HP:") else "",
                    "label": p,
                },
            }
            for p in phenotypes
        ]

        genomic_interpretations = []
        for var in variants:
            genomic_interpretations.append({
                "subjectOrBiosampleId": patient_id,
                "interpretationStatus": "CONTRIBUTORY",
                "variantInterpretation": {
                    "acmgPathogenicityClassification": var.get("classification", "UNCERTAIN_SIGNIFICANCE"),
                    "variationDescriptor": {
                        "geneContext": {"symbol": var.get("gene", "")},
                        "label": var.get("variant", ""),
                    },
                },
            })

        return {
            "id": f"phenopacket-{patient_id}-{_now_iso()}",
            "subject": {
                "id": patient_id,
            },
            "phenotypicFeatures": phenotypic_features,
            "interpretations": [
                {
                    "id": f"interpretation-{patient_id}",
                    "progressStatus": "SOLVED" if diagnosis else "UNSOLVED",
                    "diagnosis": {
                        "disease": {
                            "label": diagnosis,
                        },
                        "genomicInterpretations": genomic_interpretations,
                    } if diagnosis else {},
                }
            ] if diagnosis or genomic_interpretations else [],
            "metaData": {
                "created": _now_iso(),
                "createdBy": "HCLS AI Factory Rare Disease Diagnostic Agent",
                "phenopacketSchemaVersion": "2.0",
            },
        }
